### PR TITLE
feat: fix invalid tag

### PR DESCRIPTION
**Pull request by zhenglin-charlie-li**
Fix bug in: https://github.com/casbin/casbin-server/pull/78

fix: ERROR: invalid tag "casbin/casbin-server:": invalid reference format in GitHub Actions

### CODE REVIEW

**Comment by zhenglin-charlie-li** [comment]
The problem in the previous PR is https://github.com/casbin/casbin-server/actions/runs/3846312457/jobs/6551492385

This PR will fix the previous PR: https://github.com/casbin/casbin-server/pull/78

**Comment by nomeguy** [comment]
@ZhengLin-Li tag is still not there: https://hub.docker.com/r/casbin/casbin-server/tags

image

**Comment by zhenglin-charlie-li** [comment]
> @ZhengLin-Li tag is still not there: https://hub.docker.com/r/casbin/casbin-server/tags
> 
> image

I think this meets expectations. As far as I am concerned, this GitHub action will only push releases.

When a minor release version is available, it will be uploaded to Docker Hub. Only then can we check if it works well.

Let's check if it works correctly until next minor release.

**Comment by nomeguy** [comment]
@ZhengLin-Li the Docker in this repo should work exactly the same way as: https://hub.docker.com/r/casbin/casdoor/tags every version tag will be pushed to DockerHub as the tag itself (not to override the latest)

image

**Comment by zhenglin-charlie-li** [comment]
Yes, I understand. So in one push, it has two tags, the first one is exactly the same as the version, the second one is latest. This is the same as what is in https://github.com/casdoor/casdoor/blob/4ab2ca7a25bff1e073928a2718a82b26429300fe/.github/workflows/build.yml

```yaml
      - name: Push to Docker Hub
        tags: casbin/casbin-server:${{steps.get-current-tag.outputs.tag }},casbin/casbin-server:latest
```


What I am saying in https://github.com/casbin/casbin-server/pull/79#issuecomment-1373028722 is that, we can not check if this PR work as expected, because it will only push when there is a release. We need to wait until next release to check if this PR work correctly.

**Comment by nomeguy** [comment]
@ZhengLin-Li you can make a feat PR to test it, like improving a line in README, fixing a typo, etc.

**Comment by zhenglin-charlie-li** [comment]
> @ZhengLin-Li you can make a feat PR to test it, like improving a line in README, fixing a typo, etc.

no worry, I will keep watching it and check if it works as expected at the time of next release.

**Pull request merged**
