### PR TITLE
Update gorm adapter to v3

### LINKED ISSUE #65: Will panic when I run stress tests via ghz.
450EBDDEB19DFB646D2B233E1E352498

commacommand is:
```bash
ghz --insecure -d "{\"params\": [\"$(mkpwd 12)\", \"*\", \"POST\", \"/login\",\"*\",\"*\" ]}" 127.0.0.1:5002 --call proto.Casbin.AddPolicy
```

### PR DESCRIPTION
**Pull request by kofj**
1. Enable mysql and postgres default.
2. Update gorm adapter to v3.
3. Fix panic with  SyncedEnforcer.

Signed-off-by: 疯魔慕薇 <kfanjian@gmail.com>

Fix: https://github.com/casbin/casbin-server/issues/65

### CODE REVIEW

**Comment by kofj** [comment]
About #65

**Comment by hsluoyz** [comment]
@kofj plz improve your commit msg, too simple:

image

**Comment by hsluoyz** [comment]
@tangyang9464

**Review by tangyang9464 — APPROVED** [review]
lgtm

**Comment by tangyang9464** [comment]
@kofj I think the main content of this PR is to replace with SyncedEnforcer instead of updating gorm adapter.

**Pull request closed without merging**
