### PR TITLE
fix: some methods do not return an error

### LINKED ISSUE #48: bug: some methods do not return an error
https://github.com/casbin/casbin-server/blob/759993b8ac7e9cc70d22e485d09e8f2dd5b3444e/server/rbac_api.go#L42
https://github.com/casbin/casbin-server/blob/759993b8ac7e9cc70d22e485d09e8f2dd5b3444e/server/rbac_api.go#L202
As shown in the connection，an error should be returned

### PR DESCRIPTION
**Pull request by Angry-Chick**
The methods involved are as follows
- GetImplicitRolesForUser
- GetImplicitPermissionsForUser

fixes #48

### CODE REVIEW

**Comment by 00LT00** [comment]
Hello @Angry-Chick. Thanks for your pull request. Please fix the DCO for merge this commit

**Comment by Angry-Chick** [comment]
> Hello @Angry-Chick. Thanks for your pull request. Please fix the DCO for merge this commit

done

**Comment by hsluoyz** [comment]
@Angry-Chick plz fix:

image

**Comment by Angry-Chick** [comment]
> @Angry-Chick plz fix:
> 
> image

sorry, how can I solve this problem

**Comment by 00LT00** [comment]
@Angry-Chick 
image
update to `fix: xxxxxx`
This check works on all commits.

**Comment by Angry-Chick** [comment]
> @Angry-Chick
> image
> update to `fix: xxxxxx`
> This check works on all commits.

thx, done

**Pull request merged**
