### PR TITLE
Add casbin.pb.go to repository

### PR DESCRIPTION
**Pull request by mrfeathers**
You can't make `go get github.com/casbin/casbin-server` because there's no .go files in proto package.
```
$ go get -u github.com/casbin/casbin-server/server
package github.com/casbin/casbin-server/proto: no Go files in /home/user/go/src/github.com/casbin/casbin-server/proto
``` 
So I can't use casbin/casbin-server in my code as a dependency, I only can fork or copy casbin/casbin-server package code. I think protobuff generated code should be in git repo and should be regenerated when it's needed manually.

### CODE REVIEW

**Comment by hsluoyz** [comment]
We have the ``go generate`` command here:

https://github.com/casbin/casbin-server/blob/bbee114897632689c78071c5542db2baceae50b9/main.go#L14-L16

So you need to run ``go generate`` before ``go build`` and that file will be generated for you.

**Comment by mrfeathers** [comment]
@hsluoyz yeah, I know about `go generate`, but the problem is not in running `go build` or `go install`. The problem is downloading the package by `go get` (or `dep init`, if the package is used as a dependency). You can't get the package without `.go` files in `proto` :(

**Comment by hsluoyz** [comment]
@mrfeathers Actually, my first question is why you want to use casbin-server as a library (dependency)? casbin-server is supposed to be a self-running application. If you want to use Casbin as a library, you probably need to use: https://github.com/casbin/casbin

My second point is that there are so many projects (even libraries) that use protobuf and grpc. How do they solve this issue (generate .proto files when importing)? I don' think just committing it will be a widely used solution?

**Comment by mrfeathers** [comment]
@hsluoyz  I want to use casbin as ACaaS and here's casbin-server, but I also need some other code in this server for my infrastructure (logs, metrics, etc.), so I need use casbin-server code as a dependency.  
I've found the example of grpc server from official guide https://github.com/grpc/grpc-go/tree/master/examples/route_guide and there's .proto file and .pb.go generated file in repository, so thought it's a common practice. I'm not experienced in grpc servers, so if I'm wrong, you can cancel this PR

**Comment by hsluoyz** [comment]
I tried ``go get``, no errors related to the missing pb.go file:

```
Microsoft Windows [Version 10.0.17763.379]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\xxx>go get -v -u github.com/casbin/casbin-server
github.com/casbin/casbin-server (download)
github.com/golang/protobuf (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://google.golang.org/grpc?go-get=1
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
get "google.golang.org/grpc": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc?go-get=1
google.golang.org/grpc (download)
Fetching https://golang.org/x/net/trace?go-get=1
Parsing meta tags from https://golang.org/x/net/trace?go-get=1 (status code 200)
get "golang.org/x/net/trace": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/trace?go-get=1
get "golang.org/x/net/trace": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/internal/timeseries?go-get=1
Parsing meta tags from https://golang.org/x/net/internal/timeseries?go-get=1 (status code 200)
get "golang.org/x/net/internal/timeseries": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/internal/timeseries?go-get=1
get "golang.org/x/net/internal/timeseries": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/balancer?go-get=1
Parsing meta tags from https://google.golang.org/grpc/balancer?go-get=1 (status code 200)
get "google.golang.org/grpc/balancer": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/balancer?go-get=1
get "google.golang.org/grpc/balancer": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc?go-get=1
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
Fetching https://google.golang.org/grpc/connectivity?go-get=1
Parsing meta tags from https://google.golang.org/grpc/connectivity?go-get=1 (status code 200)
get "google.golang.org/grpc/connectivity": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/connectivity?go-get=1
get "google.golang.org/grpc/connectivity": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/grpclog?go-get=1
Parsing meta tags from https://google.golang.org/grpc/grpclog?go-get=1 (status code 200)
get "google.golang.org/grpc/grpclog": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/grpclog?go-get=1
get "google.golang.org/grpc/grpclog": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/credentials?go-get=1
Parsing meta tags from https://google.golang.org/grpc/credentials?go-get=1 (status code 200)
get "google.golang.org/grpc/credentials": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/credentials?go-get=1
get "google.golang.org/grpc/credentials": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/credentials/internal?go-get=1
Parsing meta tags from https://google.golang.org/grpc/credentials/internal?go-get=1 (status code 200)
get "google.golang.org/grpc/credentials/internal": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/credentials/internal?go-get=1
get "google.golang.org/grpc/credentials/internal": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal?go-get=1 (status code 200)
get "google.golang.org/grpc/internal": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal?go-get=1
get "google.golang.org/grpc/internal": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/metadata?go-get=1
Parsing meta tags from https://google.golang.org/grpc/metadata?go-get=1 (status code 200)
get "google.golang.org/grpc/metadata": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/metadata?go-get=1
get "google.golang.org/grpc/metadata": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/resolver?go-get=1
Parsing meta tags from https://google.golang.org/grpc/resolver?go-get=1 (status code 200)
get "google.golang.org/grpc/resolver": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/resolver?go-get=1
get "google.golang.org/grpc/resolver": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/balancer/roundrobin?go-get=1
Parsing meta tags from https://google.golang.org/grpc/balancer/roundrobin?go-get=1 (status code 200)
get "google.golang.org/grpc/balancer/roundrobin": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/balancer/roundrobin?go-get=1
get "google.golang.org/grpc/balancer/roundrobin": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/balancer/base?go-get=1
Parsing meta tags from https://google.golang.org/grpc/balancer/base?go-get=1 (status code 200)
get "google.golang.org/grpc/balancer/base": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/balancer/base?go-get=1
get "google.golang.org/grpc/balancer/base": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/grpcrand?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/grpcrand?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/grpcrand": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/grpcrand?go-get=1
get "google.golang.org/grpc/internal/grpcrand": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/codes?go-get=1
Parsing meta tags from https://google.golang.org/grpc/codes?go-get=1 (status code 200)
get "google.golang.org/grpc/codes": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/codes?go-get=1
get "google.golang.org/grpc/codes": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/encoding?go-get=1
Parsing meta tags from https://google.golang.org/grpc/encoding?go-get=1 (status code 200)
get "google.golang.org/grpc/encoding": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/encoding?go-get=1
get "google.golang.org/grpc/encoding": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/encoding/proto?go-get=1
Parsing meta tags from https://google.golang.org/grpc/encoding/proto?go-get=1 (status code 200)
get "google.golang.org/grpc/encoding/proto": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/encoding/proto?go-get=1
get "google.golang.org/grpc/encoding/proto": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/backoff?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/backoff?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/backoff": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/backoff?go-get=1
get "google.golang.org/grpc/internal/backoff": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/binarylog?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/binarylog?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/binarylog": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/binarylog?go-get=1
get "google.golang.org/grpc/internal/binarylog": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/binarylog/grpc_binarylog_v1?go-get=1
Parsing meta tags from https://google.golang.org/grpc/binarylog/grpc_binarylog_v1?go-get=1 (status code 200)
get "google.golang.org/grpc/binarylog/grpc_binarylog_v1": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/binarylog/grpc_binarylog_v1?go-get=1
get "google.golang.org/grpc/binarylog/grpc_binarylog_v1": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/status?go-get=1
Parsing meta tags from https://google.golang.org/grpc/status?go-get=1 (status code 200)
get "google.golang.org/grpc/status": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/status?go-get=1
get "google.golang.org/grpc/status": verifying non-authoritative meta tag
Fetching https://google.golang.org/genproto/googleapis/rpc/status?go-get=1
Parsing meta tags from https://google.golang.org/genproto/googleapis/rpc/status?go-get=1 (status code 200)
get "google.golang.org/genproto/googleapis/rpc/status": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at https://google.golang.org/genproto/googleapis/rpc/status?go-get=1
get "google.golang.org/genproto/googleapis/rpc/status": verifying non-authoritative meta tag
Fetching https://google.golang.org/genproto?go-get=1
Parsing meta tags from https://google.golang.org/genproto?go-get=1 (status code 200)
google.golang.org/genproto (download)
Fetching https://google.golang.org/grpc/internal/channelz?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/channelz?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/channelz": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/channelz?go-get=1
get "google.golang.org/grpc/internal/channelz": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/envconfig?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/envconfig?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/envconfig": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/envconfig?go-get=1
get "google.golang.org/grpc/internal/envconfig": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/grpcsync?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/grpcsync?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/grpcsync": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/grpcsync?go-get=1
get "google.golang.org/grpc/internal/grpcsync": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/transport?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/transport?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/transport": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/transport?go-get=1
get "google.golang.org/grpc/internal/transport": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/http2?go-get=1
Parsing meta tags from https://golang.org/x/net/http2?go-get=1 (status code 200)
get "golang.org/x/net/http2": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/http2?go-get=1
get "golang.org/x/net/http2": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/http/httpguts?go-get=1
Parsing meta tags from https://golang.org/x/net/http/httpguts?go-get=1 (status code 200)
get "golang.org/x/net/http/httpguts": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/http/httpguts?go-get=1
get "golang.org/x/net/http/httpguts": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/idna?go-get=1
Parsing meta tags from https://golang.org/x/net/idna?go-get=1 (status code 200)
get "golang.org/x/net/idna": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/idna?go-get=1
get "golang.org/x/net/idna": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/secure/bidirule?go-get=1
Parsing meta tags from https://golang.org/x/text/secure/bidirule?go-get=1 (status code 200)
get "golang.org/x/text/secure/bidirule": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/secure/bidirule?go-get=1
get "golang.org/x/text/secure/bidirule": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
golang.org/x/text (download)
Fetching https://golang.org/x/text/transform?go-get=1
Parsing meta tags from https://golang.org/x/text/transform?go-get=1 (status code 200)
get "golang.org/x/text/transform": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/unicode/bidi?go-get=1
Parsing meta tags from https://golang.org/x/text/unicode/bidi?go-get=1 (status code 200)
get "golang.org/x/text/unicode/bidi": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/unicode/bidi?go-get=1
get "golang.org/x/text/unicode/bidi": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/unicode/norm?go-get=1
Parsing meta tags from https://golang.org/x/text/unicode/norm?go-get=1 (status code 200)
get "golang.org/x/text/unicode/norm": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/http2/hpack?go-get=1
Parsing meta tags from https://golang.org/x/net/http2/hpack?go-get=1 (status code 200)
get "golang.org/x/net/http2/hpack": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/http2/hpack?go-get=1
get "golang.org/x/net/http2/hpack": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/syscall?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/syscall?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/syscall": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/syscall?go-get=1
get "google.golang.org/grpc/internal/syscall": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/keepalive?go-get=1
Parsing meta tags from https://google.golang.org/grpc/keepalive?go-get=1 (status code 200)
get "google.golang.org/grpc/keepalive": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/keepalive?go-get=1
get "google.golang.org/grpc/keepalive": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/peer?go-get=1
Parsing meta tags from https://google.golang.org/grpc/peer?go-get=1 (status code 200)
get "google.golang.org/grpc/peer": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/peer?go-get=1
get "google.golang.org/grpc/peer": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/stats?go-get=1
Parsing meta tags from https://google.golang.org/grpc/stats?go-get=1 (status code 200)
get "google.golang.org/grpc/stats": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/stats?go-get=1
get "google.golang.org/grpc/stats": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/tap?go-get=1
Parsing meta tags from https://google.golang.org/grpc/tap?go-get=1 (status code 200)
get "google.golang.org/grpc/tap": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/tap?go-get=1
get "google.golang.org/grpc/tap": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/naming?go-get=1
Parsing meta tags from https://google.golang.org/grpc/naming?go-get=1 (status code 200)
get "google.golang.org/grpc/naming": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/naming?go-get=1
get "google.golang.org/grpc/naming": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/resolver/dns?go-get=1
Parsing meta tags from https://google.golang.org/grpc/resolver/dns?go-get=1 (status code 200)
get "google.golang.org/grpc/resolver/dns": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/resolver/dns?go-get=1
get "google.golang.org/grpc/resolver/dns": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/resolver/passthrough?go-get=1
Parsing meta tags from https://google.golang.org/grpc/resolver/passthrough?go-get=1 (status code 200)
get "google.golang.org/grpc/resolver/passthrough": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/resolver/passthrough?go-get=1
get "google.golang.org/grpc/resolver/passthrough": verifying non-authoritative meta tag
github.com/casbin/casbin (download)
# cd C:\GoPath\src\github.com\casbin\casbin; git pull --ff-only
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
package github.com/casbin/casbin: exit status 128
github.com/casbin/gorm-adapter (download)
github.com/jinzhu/gorm (download)
# cd C:\GoPath\src\github.com\jinzhu\gorm; git pull --ff-only
From https://github.com/jinzhu/gorm
   5b8c0dd..8b07437  master     -> origin/master
   a659f34..f1caf05  gh-pages   -> origin/gh-pages
 * [new branch]      v2_dev     -> origin/v2_dev
 * [new tag]         v1.9       -> v1.9
 * [new tag]         v1.9.1     -> v1.9.1
 * [new tag]         v1.9.2     -> v1.9.2
error: Your local changes to the following files would be overwritten by merge:
        .github/ISSUE_TEMPLATE.md
        .github/PULL_REQUEST_TEMPLATE.md
        README.md
        association.go
        association_test.go
        callback.go
        callback_create.go
        callback_query.go
        callback_query_preload.go
        callback_save.go
        callback_update.go
        create_test.go
        customize_column_test.go
        dialect.go
        dialect_common.go
        dialect_mysql.go
        dialect_postgres.go
        dialect_sqlite3.go
        dialects/mssql/mssql.go
        dialects/postgres/postgres.go
        embedded_struct_test.go
        errors.go
        field.go
        field_test.go
        join_table_handler.go
        logger.go
        main.go
        main_test.go
        migration_test.go
        model_struct.go
        preload_test.go
        query_test.go
        scope.go
        scope_test.go
        search.go
        test_all.sh
        utils.go
        utils_test.go
        wercker.yml
Please commit your changes or stash them before you merge.
Aborting
package github.com/jinzhu/gorm: exit status 1
github.com/lib/pq (download)
# cd C:\GoPath\src\github.com\lib\pq; git pull --ff-only
From https://github.com/lib/pq
   dd1fe20..9eb73ef  master     -> origin/master
 * [new tag]         v1.0.0     -> v1.0.0
error: Your local changes to the following files would be overwritten by merge:
        .travis.sh
        .travis.yml
        README.md
        array.go
        array_test.go
        bench_test.go
        conn.go
        conn_go18.go
        conn_test.go
        copy_test.go
        doc.go
        encode.go
        encode_test.go
        error.go
        go18_test.go
        hstore/hstore.go
        listen_example/doc.go
        notify.go
        notify_test.go
        oid/gen.go
        oid/types.go
        ssl.go
        ssl_go1.7.go
        ssl_renegotiation.go
        uuid_test.go
Please commit your changes or stash them before you merge.
Aborting
package github.com/lib/pq: exit status 1
Fetching https://google.golang.org/grpc/reflection?go-get=1
Parsing meta tags from https://google.golang.org/grpc/reflection?go-get=1 (status code 200)
get "google.golang.org/grpc/reflection": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/reflection?go-get=1
get "google.golang.org/grpc/reflection": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/reflection/grpc_reflection_v1alpha?go-get=1
Parsing meta tags from https://google.golang.org/grpc/reflection/grpc_reflection_v1alpha?go-get=1 (status code 200)
get "google.golang.org/grpc/reflection/grpc_reflection_v1alpha": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/reflection/grpc_reflection_v1alpha?go-get=1
get "google.golang.org/grpc/reflection/grpc_reflection_v1alpha": verifying non-authoritative meta tag

C:\Users\xxx>
```

**Pull request closed without merging**
