### PR TITLE
Added and exposed a few more functions

### PR DESCRIPTION
**Pull request by pk82869**
Hey,

Exposed and implemented some more functions that were absent in the rbac model.
Do have a look.

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi @prathik-kaliyambath , please do not commit (and revert) the import path. Fix it in your local commits by rewrite.

**Comment by hsluoyz** [comment]
New PR proposed here: https://github.com/casbin/casbin-server/pull/30

**Comment by pk82869** [comment]
Thank you, let me know if there are any new issues to work on. Would love to contribute.

**Comment by hsluoyz** [comment]
@prathik-kaliyambath thanks for the contribution! Can you help work on this? https://github.com/casbin/casbin-server/issues/24

**Comment by pk82869** [comment]
Ok let me have a look.

**Pull request closed without merging**
